version: '3'
services:
  mcw_bot:
    build: .
    image: swaponline/mcw
    container_name: mcw_mainnet_bot
    restart: unless-stopped
    volumes:
      - ${PWD}/config:/root/currencyWallet/config
      - ${PWD}/.storage:/root/currencyWallet/.storage
      - ${PWD}/config/tradeconfig.mainnet.json:/root/CurrencyWallet/tradeconfig.mainnet.json
      - ${PWD}/config/tradeconfig.testnet.json:/root/CurrencyWallet/tradeconfig.testnet.json    
    env_file: .env
    ports:
      - "3001:3001"
